FROM debian:stretch

RUN DEBIAN_FRONTEND=noninteractive \
    apt-get update && apt-get install -y software-properties-common debian-keyring curl apt-transport-https
RUN curl https://packages.matrix.org/debian/matrix-org-archive-keyring.gpg | apt-key add -
RUN add-apt-repository -y http://matrix.org/packages/debian/
RUN DEBIAN_FRONTEND=noninteractive apt-get update
RUN DEBIAN_FRONTEND=noninteractive apt-get upgrade -y
RUN DEBIAN_FRONTEND=noninteractive \
    apt-get install -y matrix-synapse-py3=${SYNAPSE_VERSION} libpq-dev \
                       python-psycopg2
    
RUN mkdir -p /data/{media,uploads} /secret /conf /base-conf/ /var/log/synapse
VOLUME /data
VOLUME /conf
VOLUME /secret

ADD log.config /base-conf/log.config

RUN chown matrix-synapse /var/log/synapse
USER matrix-synapse

# Check /lib/systemd/system/matrix-synapse.service

CMD ["sh", "-c", ". /etc/default/matrix-synapse && cd /var/lib/matrix-synapse && exec /opt/venvs/matrix-synapse/bin/python -m synapse.app.homeserver --config-path /conf/homeserver.yaml"]
