#!/usr/bin/env bash

set -eux

version="${1:-latest}"

pupdir="$(mktemp -d)"
curl -sSL -o "$pupdir/pup.zip" https://github.com/ericchiang/pup/releases/download/v0.4.0/pup_v0.4.0_linux_amd64.zip
pushd $pupdir
unzip pup.zip
popd

pup="$pupdir/pup"

get_latest_version() {
  v="$(curl -sSL https://dl.equinox.io/ngrok/ngrok/stable | \
    $pup '.version text{}')"
  echo "${v#"Version "}"
}

get_ngrok_download() {
  local version="${1:?version}"
  # I couldn't figure out how to do this in a single pup expression
  curl -sSL https://dl.equinox.io/ngrok/ngrok/stable/archive | \
    $pup '.release:parent-of(h2:contains("Version '"$version"'")) .platform:parent-of(.logo:parent-of(span:contains("Linux"))) .link:parent-of(.arch:contains("64-bit"))'| \
    $pup ':parent-of(.archive:contains("zip")) a attr{href}'
}

if [[ "$version" == latest ]]; then
  version="$(get_latest_version)"
fi

url="$(get_ngrok_download "$version")"

ngrok_url="$url" gotmpl -env < Dockerfile.tmpl > Dockerfile

docker build -t "euank/ngrok:${version}" .
